drop schema if exists service cascade;
create schema if not exists service;

create table service.users
(
    id       integer generated by default as identity (start with 1) primary key,
    email    varchar(50) unique,
    password varchar(50) unique
);